// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUQhgyTtQ9PWVCAlf81QU__f4kCWsWX0w',
    appId: '1:814203782361:android:a7d44f9a73e45043deaac8',
    messagingSenderId: '814203782361',
    projectId: 'quit-smoking-tracker-f4bbb',
    storageBucket: 'quit-smoking-tracker-f4bbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5xeU_G5CaJQuZMdD1lEfZjXnGMcE6lOg',
    appId: '1:814203782361:ios:d3ac25e99a065a09deaac8',
    messagingSenderId: '814203782361',
    projectId: 'quit-smoking-tracker-f4bbb',
    storageBucket: 'quit-smoking-tracker-f4bbb.firebasestorage.app',
    iosClientId: '814203782361-1eurk9g6650en2l9pro6ait4akm6f7tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuitSmoking',
  );
}
